//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.05 at 11:01:25 吮爬 CST 
//


package sacred.alliance.magic.app.map.point;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import sacred.alliance.magic.vo.Point;


/**
 * <p>Java class for CollectPointConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CollectPointConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nodes" type="{}PointNode" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="config")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CollectPointConfig", propOrder = {
    "nodes"
})
public class CollectPointConfig {

    protected List<PointNode> nodes = new ArrayList<PointNode>();

    /**
     * Gets the value of the nodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PointNode }
     * 
     * 
     */
    public List<PointNode> getNodes() {
        if (nodes == null) {
            nodes = new ArrayList<PointNode>();
        }
        return this.nodes;
    }

	public void setNodes(List<PointNode> nodes) {
		this.nodes = nodes;
	}
	
	public Point getRandomPoint(String eventId){
		if(null == eventId || 0 == eventId.trim().length()){
			return null ;
		}
		if(null == nodes || 0 == this.nodes.size()){
			return null ;
		}
		for(PointNode node : nodes){
			if(node.getId().equals(eventId)){
				return node.getRandomPoint() ;
			}
		}
		return null ;
	}
	
	public void  init(String mapId){
		if(null == nodes || 0 == this.nodes.size()){
			return  ;
		}
		for(PointNode node : nodes){
			node.init(mapId);
		}
	}
}


