//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 06:12:18 芟爬 CST 
//



package sacred.alliance.magic.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Way complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Way">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="point1" type="{}Point"/>
 *         &lt;element name="point2" type="{}Point"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Way", propOrder = {
    "point1",
    "point2"
})
public class Way {

    @XmlElement(required = true)
    protected Point point1;
    @XmlElement(required = true)
    protected Point point2;
    @XmlAttribute
    private Integer distance;

    /**
     * Gets the value of the point1 property.
     * 
     * @return
     *     possible object is
     *     {@link Point }
     *     
     */
    public Point getPoint1() {
        return point1;
    }

    /**
     * Sets the value of the point1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Point }
     *     
     */
    public void setPoint1(Point value) {
        this.point1 = value;
        distance = null ;
    }

    /**
     * Gets the value of the point2 property.
     * 
     * @return
     *     possible object is
     *     {@link Point }
     *     
     */
    public Point getPoint2() {
        return point2;
    }

    /**
     * Sets the value of the point2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Point }
     *     
     */
    public void setPoint2(Point value) {
        this.point2 = value;
        distance = null ;
    }

    
    public Way(){
    	
    }
    
    public Way(Point point1,Point point2){
    	this.point1 = point1 ;
    	this.point2 = point2 ;
    	distance = null ;
    }

	public int getDistance() {
		if(null == point1 || null == point2){
			return 0 ;
		}
		if(null == distance){
			this.distance = Math.abs(point1.getX() - point2.getX()) + Math.abs(point1.getY()-point2.getY());
		}
		return distance;
	}
    
    
}
