//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.25 at 08:40:02 下午 CST 
//


package sacred.alliance.magic.app.map.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuildData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuildData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="buildlayer" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="drawx" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="drawy" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="imageid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="imagename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="xnum" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ynum" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="builddata")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuildData")
public class BuildData {

    @XmlAttribute
    protected int buildlayer;//层
    @XmlAttribute
    protected int drawx;//画图片的X坐标
    @XmlAttribute
    protected int drawy;//画图片的Y坐标
    @XmlAttribute
    protected int imageid;//图片ID
    @XmlAttribute
    protected String imagename = "";
    @XmlAttribute
    protected int x; //中心框的X坐标
    @XmlAttribute
    protected int xnum;//X的个数
    @XmlAttribute
    protected int y;//中心框的Y坐标
    @XmlAttribute
    protected int ynum;//Y的个数
	public int getBuildlayer() {
		return buildlayer;
	}
	public void setBuildlayer(int buildlayer) {
		this.buildlayer = buildlayer;
	}
	public int getDrawx() {
		return drawx;
	}
	public void setDrawx(int drawx) {
		this.drawx = drawx;
	}
	public int getDrawy() {
		return drawy;
	}
	public void setDrawy(int drawy) {
		this.drawy = drawy;
	}
	public int getImageid() {
		return imageid;
	}
	public void setImageid(int imageid) {
		this.imageid = imageid;
	}
	public String getImagename() {
		return imagename;
	}
	public void setImagename(String imagename) {
		this.imagename = imagename;
	}
	public int getX() {
		return x;
	}
	public void setX(int x) {
		this.x = x;
	}
	public int getXnum() {
		return xnum;
	}
	public void setXnum(int xnum) {
		this.xnum = xnum;
	}
	public int getY() {
		return y;
	}
	public void setY(int y) {
		this.y = y;
	}
	public int getYnum() {
		return ynum;
	}
	public void setYnum(int ynum) {
		this.ynum = ynum;
	}

   

}
