//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.25 at 09:55:35 下午 CST 
//


package sacred.alliance.magic.app.map.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import sacred.alliance.magic.base.MapLogicType;


/**
 * <p>Java class for MapConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MapConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="maplogicid" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="samecampcanpk" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="diffcampcanpk" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="cantroop" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="copymode" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="deathjumpmapid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reloginjumpmapid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maporiginx" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="maporiginy" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="maptype" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="mapweather" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="mapconfig")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MapConfig")
public class MapConfig {

    @XmlAttribute
    protected int maplogicid;
    @XmlAttribute
    protected boolean samecampcanpk;
    @XmlAttribute
    protected boolean diffcampcanpk;
    @XmlAttribute
    protected boolean cantroop;
    @XmlAttribute
    protected byte logictype;//MapLogicType类型标识
    @XmlAttribute
    protected String deathjumpmapid;
    @XmlAttribute
    protected String reloginjumpmapid;
    @XmlAttribute
    protected int maporiginx;//安全点
    @XmlAttribute
    protected int maporiginy;//安全点
    @XmlAttribute
    protected byte maptype;
    @XmlAttribute
    protected byte mapweather;
    @XmlAttribute
    protected String maplevelname; //关卡名
    @XmlAttribute
    protected String mapdisplayname;
    @XmlAttribute
    protected String mapgroundres ;//地图资源
    @XmlAttribute
    protected int mapmusicindex = -1 ;
    @XmlAttribute
    protected byte isEquestrian = 1;// 是否能使用骑术技能，0：不能，1：能
    
    private boolean hadLineMap = false; //是否为分线地图
    private int maxRoleCount = -1;//地图支持最大人数（-1：不受人数限制）
    private int maxLineCount = -1; //地图最大分线数目(-1：不受限制)
    private int lifeCycle = 120; //地图无玩家时的销毁间隔时间（单位：秒）
    
    private short copyId = -1; //副本ID
    
    
    /**通天塔(添加)*/
    private String towerId;//通天塔ID
    private int order;//地图序号
    private boolean lastMap = false;//最后一张地图(true : 可以翻牌)
    private boolean firstMap = false;//第一张地图(true:第一张允许进入)
    private int gateIndex;//位置下标
    private int currGateMapIndex;//当前关卡的地图下标(每个关卡都由1-9)
    private int timeover = 0 ; //当前地图超时时间
    
    private short smallMapResId ; //小地图资源ID,从配置表中获得
    private int minTransLevel ; //传输级别
    private int maxTransLevel ; //传输级别
    private int weatherTimes = -1 ; 
    private byte showExit ; //是否显示出口
    private byte npcPK ; //npc是否可PK
    private int broadcastAllMax = 0;
    private int changeLine;//是否允许变线
    private byte roleCanPK;//是否可以强制PK 0否 1是
    
    public boolean isPvpMap(){
    	return this.samecampcanpk || this.diffcampcanpk || this.roleCanPK == 1;
    }
    
	public int getMaplogicid() {
		return maplogicid;
	}
	public void setMaplogicid(int maplogicid) {
		this.maplogicid = maplogicid;
	}
	public boolean isSamecampcanpk() {
		return samecampcanpk;
	}
	public void setSamecampcanpk(boolean samecampcanpk) {
		this.samecampcanpk = samecampcanpk;
	}
	public boolean isDiffcampcanpk() {
		return diffcampcanpk;
	}
	public void setDiffcampcanpk(boolean diffcampcanpk) {
		this.diffcampcanpk = diffcampcanpk;
	}
	public boolean isCantroop() {
		return cantroop;
	}
	public void setCantroop(boolean cantroop) {
		this.cantroop = cantroop;
	}
	public String getDeathjumpmapid() {
		return deathjumpmapid;
	}
	public void setDeathjumpmapid(String deathjumpmapid) {
		this.deathjumpmapid = deathjumpmapid;
	}
	public String getReloginjumpmapid() {
		return reloginjumpmapid;
	}
	public void setReloginjumpmapid(String reloginjumpmapid) {
		this.reloginjumpmapid = reloginjumpmapid;
	}
	public int getMaporiginx() {
		return maporiginx;
	}
	public void setMaporiginx(int maporiginx) {
		this.maporiginx = maporiginx;
	}
	public int getMaporiginy() {
		return maporiginy;
	}
	public void setMaporiginy(int maporiginy) {
		this.maporiginy = maporiginy;
	}
	public byte getMaptype() {
		return maptype;
	}
	public void setMaptype(byte maptype) {
		this.maptype = maptype;
	}
	public byte getMapweather() {
		return mapweather;
	}
	public void setMapweather(byte mapweather) {
		this.mapweather = mapweather;
	}
	
	public String getMapdisplayname() {
		return mapdisplayname;
	}
	public void setMapdisplayname(String mapdisplayname) {
		this.mapdisplayname = mapdisplayname;
	}

    public String getMapgroundres() {
        return mapgroundres;
    }

    public void setMapgroundres(String mapgroundres) {
        this.mapgroundres = mapgroundres;
    }

    public String getMaplevelname() {
        return maplevelname;
    }

    public void setMaplevelname(String maplevelname) {
        this.maplevelname = maplevelname;
    }
	public int getMapmusicindex() {
		return mapmusicindex;
	}
	public byte getIsEquestrian() {
		return isEquestrian;
	}
	public void setIsEquestrian(byte isEquestrian) {
		this.isEquestrian = isEquestrian;
	}
	
	/**
	 * 判断地图类型是否为副本地图
	 * @return
	 */
	public boolean iscopymode(){
		return MapLogicType.isCopyType(this.logictype);
	}
	
	
	public MapLogicType getMapLogicType(){
		return MapLogicType.getMapLogicType(this.logictype);
	}
	
	public byte getLogictype() {
		return logictype;
	}
	public void setLogictype(byte logictype) {
		this.logictype = logictype;
	}
	public int getOrder() {
		return order;
	}
	public void setOrder(int order) {
		this.order = order;
	}
	public boolean isLastMap() {
		return lastMap;
	}
	public void setLastMap(boolean lastMap) {
		this.lastMap = lastMap;
	}
	public String getTowerId() {
		return towerId;
	}
	public void setTowerId(String towerId) {
		this.towerId = towerId;
	}
	public boolean isFirstMap() {
		return firstMap;
	}
	public void setFirstMap(boolean firstMap) {
		this.firstMap = firstMap;
	}
	
	public int getCurrGateMapIndex() {
		return currGateMapIndex;
	}
	public void setCurrGateMapIndex(int currGateMapIndex) {
		this.currGateMapIndex = currGateMapIndex;
	}
	public int getGateIndex() {
		return gateIndex;
	}
	public void setGateIndex(int gateIndex) {
		this.gateIndex = gateIndex;
	}
	public int getMaxRoleCount() {
		return maxRoleCount;
	}
	public void setMaxRoleCount(int maxRoleCount) {
		this.maxRoleCount = maxRoleCount;
	}
	public int getMaxLineCount() {
		return maxLineCount;
	}
	public void setMaxLineCount(int maxLineCount) {
		this.maxLineCount = maxLineCount;
	}
	public int getLifeCycle() {
		return lifeCycle;
	}
	public void setLifeCycle(int lifeCycle) {
		this.lifeCycle = lifeCycle;
	}
	public boolean isHadLineMap() {
		return hadLineMap;
	}
	public void setHadLineMap(boolean hadLineMap) {
		this.hadLineMap = hadLineMap;
	}
	public short getCopyId() {
		return copyId;
	}
	public void setCopyId(short copyId) {
		this.copyId = copyId;
	}

	public short getSmallMapResId() {
		return smallMapResId;
	}

	public void setSmallMapResId(short smallMapResId) {
		this.smallMapResId = smallMapResId;
	}

	public int getWeatherTimes() {
		return weatherTimes;
	}

	public void setWeatherTimes(int weatherTimes) {
		this.weatherTimes = weatherTimes;
	}

	public void setMapmusicindex(int mapmusicindex) {
		this.mapmusicindex = mapmusicindex;
	}

	public byte getShowExit() {
		return showExit;
	}

	public void setShowExit(byte showExit) {
		this.showExit = showExit;
	}
	
	
	public boolean changeLogicType(MapLogicType type){
		if(null == type){
			return false ;
		}
		if(this.logictype == MapLogicType.defaultLogic.getType()
				|| this.logictype == type.getType()){
			this.logictype = (byte)type.getType() ;
			return true ;
		}
		return false ;
	}

	public byte getNpcPK() {
		return npcPK;
	}

	public void setNpcPK(byte npcPK) {
		this.npcPK = npcPK;
	}

	public int getTimeover() {
		return timeover;
	}

	public void setTimeover(int timeover) {
		this.timeover = timeover;
	}

	public int getBroadcastAllMax() {
		return broadcastAllMax;
	}

	public void setBroadcastAllMax(int broadcastAllMax) {
		this.broadcastAllMax = broadcastAllMax;
	}

	public int getMinTransLevel() {
		return minTransLevel;
	}

	public void setMinTransLevel(int minTransLevel) {
		this.minTransLevel = minTransLevel;
	}

	public int getMaxTransLevel() {
		return maxTransLevel;
	}

	public void setMaxTransLevel(int maxTransLevel) {
		this.maxTransLevel = maxTransLevel;
	}

	public int getChangeLine() {
		return changeLine;
	}

	public void setChangeLine(int changeLine) {
		this.changeLine = changeLine;
	}

	public byte getRoleCanPK() {
		return roleCanPK;
	}

	public void setRoleCanPK(byte roleCanPK) {
		this.roleCanPK = roleCanPK;
	}
}
