//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.26 at 02:21:28 下午 CST 
//


package sacred.alliance.magic.app.map.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NpcBorn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NpcBorn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="bornmapgxbegin" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="bornmapgybegin" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="bornmapgxend" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="bornmapgyend" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="bornnpccount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="bornnpcid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minrefreshsecond" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="maxrefreshsecond" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="starttime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="endtime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pathtype" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="pathid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NpcBorn")
public class NpcBorn {

	@XmlAttribute
	protected int bornNpcDir ;//方位（0=随机,1=右,2=下,3=左,4=上）
    @XmlAttribute
    protected int bornmapgxbegin;//坐标X最小值
    @XmlAttribute
    protected int bornmapgybegin;//坐标Y最小值
    @XmlAttribute
    protected int bornmapgxend;//坐标X最大值
    @XmlAttribute
    protected int bornmapgyend;//坐标Y最大值
    @XmlAttribute
    protected int bornnpccount;//NPC数量
    @XmlAttribute
    protected String bornnpcid;//NPC的ID
    @XmlAttribute
    protected int minrefreshsecond;//死亡刷新最小时间（秒）
    @XmlAttribute
    protected int maxrefreshsecond;//死亡刷新最大时间（秒）
    @XmlAttribute
    protected String starttime;
    @XmlAttribute
    protected String endtime;
    @XmlAttribute
    protected int pathtype;
    @XmlAttribute
    protected String pathid;
    @XmlAttribute
    protected byte pal = -1;
    @XmlAttribute
    protected byte mmp = -1;
    @XmlAttribute
    protected int startdate =  -1;
    @XmlAttribute
    protected int enddate = -1;
    @XmlAttribute
    protected int refreshcycle = -1;
    @XmlAttribute
    protected int isDisappear = -1;
    
	public int getBornmapgxbegin() {
		return bornmapgxbegin;
	}
	public void setBornmapgxbegin(int bornmapgxbegin) {
		this.bornmapgxbegin = bornmapgxbegin;
	}
	public int getBornmapgybegin() {
		return bornmapgybegin;
	}
	public void setBornmapgybegin(int bornmapgybegin) {
		this.bornmapgybegin = bornmapgybegin;
	}
	public int getBornmapgxend() {
		return bornmapgxend;
	}
	public void setBornmapgxend(int bornmapgxend) {
		this.bornmapgxend = bornmapgxend;
	}
	public int getBornmapgyend() {
		return bornmapgyend;
	}
	public void setBornmapgyend(int bornmapgyend) {
		this.bornmapgyend = bornmapgyend;
	}
	public int getBornnpccount() {
		return bornnpccount;
	}
	public void setBornnpccount(int bornnpccount) {
		this.bornnpccount = bornnpccount;
	}
	public String getBornnpcid() {
		return bornnpcid;
	}
	public void setBornnpcid(String bornnpcid) {
		this.bornnpcid = bornnpcid;
	}
	public int getMinrefreshsecond() {
		return minrefreshsecond;
	}
	public void setMinrefreshsecond(int minrefreshsecond) {
		this.minrefreshsecond = minrefreshsecond;
	}
	public int getMaxrefreshsecond() {
		return maxrefreshsecond;
	}
	public void setMaxrefreshsecond(int maxrefreshsecond) {
		this.maxrefreshsecond = maxrefreshsecond;
	}
	public String getStarttime() {
		return starttime;
	}
	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}
	public String getEndtime() {
		return endtime;
	}
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}
	public int getPathtype() {
		return pathtype;
	}
	public void setPathtype(int pathtype) {
		this.pathtype = pathtype;
	}
	public String getPathid() {
		return pathid;
	}
	public void setPathid(String pathid) {
		this.pathid = pathid;
	}
	public int getBornNpcDir() {
		return bornNpcDir;
	}
	public void setBornNpcDir(int bornNpcDir) {
		this.bornNpcDir = bornNpcDir;
	}
	public byte getPal() {
		return pal;
	}
	public void setPal(byte pal) {
		this.pal = pal;
	}
	public byte getMmp() {
		return mmp;
	}
	public void setMmp(byte mmp) {
		this.mmp = mmp;
	}
	public int getStartdate() {
		return startdate;
	}
	public void setStartdate(int startdate) {
		this.startdate = startdate;
	}
	public int getEnddate() {
		return enddate;
	}
	public void setEnddate(int enddate) {
		this.enddate = enddate;
	}
	public int getRefreshcycle() {
		return refreshcycle;
	}
	public void setRefreshcycle(int refreshcycle) {
		this.refreshcycle = refreshcycle;
	}
	public int getIsDisappear() {
		return isDisappear;
	}
	public void setIsDisappear(int isDisappear) {
		this.isDisappear = isDisappear;
	}
	
	public boolean canReborn(){
		return this.minrefreshsecond >=0 && this.maxrefreshsecond >0;
	}
}
