//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.29 at 05:34:16 下午 CST 
//


package sacred.alliance.magic.app.map.point;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JumpMapPointCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JumpMapPointCollection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="points" type="{}JumpMapPoint" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="points")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JumpMapPointCollection", propOrder = {
    "point"
})
public class JumpMapPointCollection {

	public JumpMapPointCollection(){
		
	}
	
	public JumpMapPointCollection(List<JumpMapPoint> point){
		this.point = point;
	}
	
    protected List<JumpMapPoint> point = new ArrayList<JumpMapPoint>();

    /**
     * Gets the value of the points property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the points property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JumpMapPoint }
     * 
     * 
     */
    public List<JumpMapPoint> getPoint() {
        if (point == null) {
            point = new ArrayList<JumpMapPoint>();
        }
        return this.point;
    }
    
    /**
     * 获取自己阵营的跳转点集合
     * tocamp字段:
     * 		-1：不分阵营的跳转点
     *		0：帝国
     * 		1：同盟
     */
    public List<JumpMapPoint> getPointList(){
    	if (point == null) {
            point = new ArrayList<JumpMapPoint>();
        }
    	List<JumpMapPoint> JumpMapPoints = new ArrayList<JumpMapPoint>();
    	JumpMapPoints.addAll(point);
    	/*try{
    		//int camp ;
    		//int force ;
	    	for(JumpMapPoint p : point){
	    		//camp = p.getTocamp();
	    		//force = ForceType.getTypeByRace(raceType).getValue();
	    		//if(camp == -1 || camp == force){
	    			JumpMapPoints.add(p);
	    		//}
	    	}
    	}catch(Exception e){
    		e.printStackTrace();
    	}*/
    	return JumpMapPoints;
    }

	public void setPoint(List<JumpMapPoint> point) {
		this.point = point;
	}

    
}
